### ISSUE TITLE
Pancakeswap Error

### ISSUE THREAD

**Issue by Hailiebaby16** [jklepatch/eattheblocks#119]
Whenever i run your code it says eth_subscribe does not exist. Whats happening here?

**Comment by bvp416** [comment]
`Error: The method eth_subscribe does not exist/is not available
    at WebSocketProvider._this._websocket.onmessage (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/@ethersproject/providers/lib/websocket-provider.js:123:33)
    at WebSocket.onMessage (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/Users/brendonp-liatrio/git/personal/eattheblocks/screencast/348-pancakeswap-trading-bot/node_modules/ws/lib/receiver.js:77:10)
    at writeOrBuffer (node:internal/streams/writable:389:12) {
  code: -32601,
  response: '{"id":1,"jsonrpc":"2.0","error":{"faq":"https://ankr-network.github.io","issues":"https://github.com/Ankr-network/ankr-service","code":-32601,"message":"The method eth_subscribe does not exist/is not available"}}'
}`

**Comment by Hailiebaby16** [comment]
Whats that code means sir?

**Comment by bvp416** [comment]
It's the error message that we're both seeing.

**Comment by theterrapunk** [comment]
I'm getting the same error. Will update if I find anything useful

**Comment by theterrapunk** [comment]
This is a weird one. I'm not sure exactly how I fixed it, but I did the following things and now it is working great:
1) Update NPM and Node to latest version
2) Try creating a new Ankr API endpoint for BSC
3) Make sure you have the one starting with "wss" pasted into your provider variable
