### ISSUE TITLE
followed instructions in your course doesnt work 

### ISSUE THREAD

**Issue by adamrg73** [jklepatch/eattheblocks#16]
2020-09-19T15:50:26.484916+00:00 app[arbitrage.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-09-19T15:50:26.484917+00:00 app[arbitrage.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-09-19T15:50:26.484917+00:00 app[arbitrage.1]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-09-19T15:50:26.484918+00:00 app[arbitrage.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-09-19T15:50:26.484918+00:00 app[arbitrage.1]:     at internal/main/run_main_module.js:17:47 {
2020-09-19T15:50:26.484919+00:00 app[arbitrage.1]:   code: 'MODULE_NOT_FOUND',
2020-09-19T15:50:26.484919+00:00 app[arbitrage.1]:   requireStack: [ '/app/run-arbitrage.js' ]
2020-09-19T15:50:26.484920+00:00 app[arbitrage.1]: }
2020-09-19T15:50:26.537412+00:00 heroku[arbitrage.1]: Process exited with status 1
2020-09-19T15:50:26.583714+00:00 heroku[arbitrage.1]: State changed from up to crashed
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2020-09-19T15:50:26.484916+00:00 app[arbitrage.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-09-19T15:50:26.484917+00:00 app[arbitrage.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-09-19T15:50:26.484917+00:00 app[arbitrage.1]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-09-19T15:50:26.484918+00:00 app[arbitrage.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-09-19T15:50:26.484918+00:00 app[arbitrage.1]:     at internal/main/run_main_module.js:17:47 {
2020-09-19T15:50:26.484919+00:00 app[arbitrage.1]:   code: 'MODULE_NOT_FOUND',
2020-09-19T15:50:26.484919+00:00 app[arbitrage.1]:   requireStack: [ '/app/run-arbitrage.js' ]
2020-09-19T15:50:26.484920+00:00 app[arbitrage.1]: }
2020-09-19T15:50:26.537412+00:00 heroku[arbitrage.1]: Process exited with status 1
2020-09-19T15:50:26.583714+00:00 heroku[arbitrage.1]: State changed from up to crashed
2020-09-19T16:22:07.834102+00:00 heroku[arbitrage.1]: State changed from crashed to starting
2020-09-19T16:22:12.116264+00:00 heroku[arbitrage.1]: Starting process with command `node run-arbitrage.js`
2020-09-19T16:22:12.752070+00:00 heroku[arbitrage.1]: State changed from starting to up
2020-09-19T16:22:15.110603+00:00 heroku[arbitrage.1]: Process exited with status 1
2020-09-19T16:22:15.158677+00:00 heroku[arbitrage.1]: State changed from up to crashed
2020-09-19T16:22:15.031185+00:00 app[arbitrage.1]: internal/modules/cjs/loader.js:968
2020-09-19T16:22:15.031200+00:00 app[arbitrage.1]:   throw err;
2020-09-19T16:22:15.031200+00:00 app[arbitrage.1]:   ^
2020-09-19T16:22:15.031201+00:00 app[arbitrage.1]: 
2020-09-19T16:22:15.031201+00:00 app[arbitrage.1]: Error: Cannot find module './build/contracts/Flashloan.json'
2020-09-19T16:22:15.031202+00:00 app[arbitrage.1]: Require stack:
2020-09-19T16:22:15.031202+00:00 app[arbitrage.1]: - /app/run-arbitrage.js
2020-09-19T16:22:15.031203+00:00 app[arbitrage.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
2020-09-19T16:22:15.031203+00:00 app[arbitrage.1]:     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
2020-09-19T16:22:15.031204+00:00 app[arbitrage.1]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-09-19T16:22:15.031204+00:00 app[arbitrage.1]:     at require (internal/modules/cjs/helpers.js:72:18)
2020-09-19T16:22:15.031205+00:00 app[arbitrage.1]:     at Object.<anonymous> (/app/run-arbitrage.js:6:19)
2020-09-19T16:22:15.031205+00:00 app[arbitrage.1]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2020-09-19T16:22:15.031205+00:00 app[arbitrage.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-09-19T16:22:15.031206+00:00 app[arbitrage.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-09-19T16:22:15.031206+00:00 app[arbitrage.1]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-09-19T16:22:15.031207+00:00 app[arbitrage.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-09-19T16:22:15.031207+00:00 app[arbitrage.1]:     at internal/main/run_main_module.js:17:47 {
2020-09-19T16:22:15.031207+00:00 app[arbitrage.1]:   code: 'MODULE_NOT_FOUND',
2020-09-19T16:22:15.031208+00:00 app[arbitrage.1]:   requireStack: [ '/app/run-arbitrage.js' ]
2020-09-19T16:22:15.031208+00:00 app[arbitrage.1]: }

**Comment by diaspogift** [comment]
Hi I am running into the same issue. Any solution to this issue?
