### ISSUE TITLE
PancakeSwap Trading Bot: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by johndoe75** [jklepatch/eattheblocks#64]
This issue relates to "348-pancakeswap-trading-bot".  I'm running your code 1:1 without any changes except for the WebSocket URL of my Ankr project.  Everytime I start, I'm getting this error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1095:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ClientRequest.req.on (/root/bsc-sniper-bot/node_modules/ws/lib/websocket.js:555:15)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I've tried it at my desktop, on a server (other network) and at my work laptop.  Always the same result.  None of the computers does having a proxy setup or alike.

**Comment by djammy33** [comment]
Can you check the following

Press the Windows Key
Search For Internet Options
Click on "Internet Options"
Click On "Connection"
Go to LAN Settings
Is there a checkmark in "Use Proxy Server for LAN" ? If so, try unchecking it

**Comment by johndoe75** [comment]
I've tripple checked my network settings: no proxy setup (MacOS).

Also I've tried to run the code on two different hosted Linux server at different hoster as well – outside my network (Node v10.19.0) to exclude any issues with my network. Same result.

**Comment by johndoe75** [comment]
First wasn't working this morning, then suddenly it worked.  I suspect the issue to be on side of Ankr.
